image:https://github.com/dessertj/dessertj-core/actions/workflows/maven.yml/badge.svg[CI, link=https://github.com/dessertj/dessertj-core/actions/workflows/maven.yml?query=branch%3Amaster++]
image:https://maven-badges.herokuapp.com/maven-central/org.dessertj/dessertj-core/badge.svg[Maven Central, link=https://search.maven.org/search?q=g%3Aorg.dessertj%20a%3Adessertj-core]
image:https://img.shields.io/github/license/dessertj/dessertj-core.svg[License, link=https://github.com/dessertj/dessertj-core/blob/master/LICENSE.md]

= DessertJ Dependency Assertion Library for Java

The name *dessertj* comes from **de**pendency a**ssert** for **Java**.
Hence, *dessertj* is a library for unit-tests to check dependencies between classes.
It's used to keep an architecture clean.

Simply said an architecture is something you can express with
a https://en.wikipedia.org/wiki/Block_diagram[block diagram],
that is a diagram with blocks and arrows between them.
A block is an arbitrary part of a software-system. The arrows show the
dependencies between the blocks.

DessertJ provides an API to write down such block diagrams in Java code:
The `Slice` interface represents a block. DessertJ has many ways
to specify what belongs to such a block.
DessertJ's assertion API expresses the dependencies between the block.

Can you see the advantage? If you use this API to describe your
architecture within a unit-test, it will ensure reality matches
the design each time the test is run.

== Getting started

Add the _dessertj-core_ dependency:

----
<dependency>
    <groupId>org.dessertj</groupId>
    <artifactId>dessertj-core</artifactId>
    <version>0.6.1</version>
    <scope>test</scope>
</dependency>
----

Write your first test:
[code, java]
----
package org.dessertj.samples;

import org.dessertj.slicing.Classpath;
import org.dessertj.slicing.Slice;
import org.junit.Test;

import static org.dessertj.assertions.SliceAssertions.assertThatSlice;

public class SampleTest {
    private static final Classpath cp = new Classpath();

    @Test
    public void detectUsageOfJdkInternalApis() {
        Slice myCompanyCode = cp.slice("de.spricom..*");
        Slice jdkInternalApis = cp.slice("sun..*").plus(cp.slice("com.sun..*"));
        assertThatSlice(myCompanyCode).doesNotUse(jdkInternalApis);
    }
}
----

For more information see https://dessertj.org/[dessertj.org].

== License

The dessertj-core library is published under the Apache License 2.0, +
see http://www.apache.org/licenses/LICENSE-2.0 for details.

There are no third party libraries required.