package de.spricom.dessert.samples;

/*-
 * #%L
 * Dessert Dependency Assertion Library for Java
 * %%
 * Copyright (C) 2017 - 2021 Hans Jörg Heßmann
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import de.spricom.dessert.classfile.ClassFile;
import de.spricom.dessert.samples.annotations.*;
import org.junit.Test;

import java.io.IOException;
import java.util.Set;

import static org.fest.assertions.Assertions.assertThat;

/**
 * This test has been generated by TestGeneratorTool.
 */
public class AnnotationsTest {

    @Test
    public void testAnnotatedObject() throws IOException {
        ClassFile cf = new ClassFile(AnnotatedObject.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.annotations.SampleAnnotation",
                "de.spricom.dessert.samples.enums.SomeEnum",
                "java.lang.Object");
    }

    @Test
    public void testMetaAnnotatedObject() throws IOException {
        ClassFile cf = new ClassFile(MetaAnnotatedObject.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.annotations.Val3Annotation",
                "java.lang.Object");
    }

    @Test
    public void testSampleAnnotation() throws IOException {
        ClassFile cf = new ClassFile(SampleAnnotation.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.enums.SomeEnum",
                "java.lang.Object",
                "java.lang.annotation.Annotation",
                "java.lang.annotation.Documented",
                "java.lang.annotation.ElementType",
                "java.lang.annotation.Inherited",
                "java.lang.annotation.Retention",
                "java.lang.annotation.RetentionPolicy",
                "java.lang.annotation.Target");
    }

    @Test
    public void testSpecialArg() throws IOException {
        ClassFile cf = new ClassFile(SpecialArg.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "java.lang.Object",
                "java.lang.annotation.Annotation",
                "java.lang.annotation.ElementType",
                "java.lang.annotation.Retention",
                "java.lang.annotation.RetentionPolicy",
                "java.lang.annotation.Target");
    }

    @Test
    public void testSpecialArgSample() throws IOException {
        ClassFile cf = new ClassFile(SpecialArgSample.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.annotations.SpecialArg",
                "java.io.PrintStream",
                "java.lang.Object",
                "java.lang.String",
                "java.lang.StringBuilder",
                "java.lang.System");
    }

    @Test
    public void testVal3Annotation() throws IOException {
        ClassFile cf = new ClassFile(Val3Annotation.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.annotations.SampleAnnotation",
                "de.spricom.dessert.samples.enums.SomeEnum",
                "java.lang.Object",
                "java.lang.annotation.Annotation",
                "java.lang.annotation.ElementType",
                "java.lang.annotation.Retention",
                "java.lang.annotation.RetentionPolicy",
                "java.lang.annotation.Target");
    }

}
