package de.spricom.dessert.samples;

/*-
 * #%L
 * Dessert Dependency Assertion Library for Java
 * %%
 * Copyright (C) 2017 - 2021 Hans Jörg Heßmann
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import de.spricom.dessert.classfile.ClassFile;
import de.spricom.dessert.samples.exceptions.BaseException;
import de.spricom.dessert.samples.exceptions.SubException;
import de.spricom.dessert.samples.exceptions.ThrowSubException;
import org.junit.Test;

import java.io.IOException;
import java.util.Set;

import static org.fest.assertions.Assertions.assertThat;

/**
 * This test has been generated by TestGeneratorTool.
 */
public class ExceptionsTest {

    @Test
    public void testBaseException() throws IOException {
        ClassFile cf = new ClassFile(BaseException.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "java.lang.Exception");
    }

    @Test
    public void testSubException() throws IOException {
        ClassFile cf = new ClassFile(SubException.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.basic.Foo",
                "de.spricom.dessert.samples.exceptions.BaseException");
    }

    @Test
    public void testThrowSubException() throws IOException {
        ClassFile cf = new ClassFile(ThrowSubException.class);
        Set<String> dependentClasses = cf.getDependentClasses();
        assertThat(dependentClasses).containsOnly(
                "de.spricom.dessert.samples.basic.Foo",
                "de.spricom.dessert.samples.exceptions.BaseException",
                "de.spricom.dessert.samples.exceptions.SubException",
                "java.lang.Object");
    }

}
