# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK's
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: |
          8
          11
        mvn-toolchain-id: |
          jdk8
          jdk11
        cache: maven

    - run: ls -l ~/.m2
    - run: cat ~/.m2/toolchains.xml
    - run: cat ~/.m2/settings.xml
    - run: java -version
    - run: which java

    - name: Build dessertj-core-java9 with Maven
      run: . mvnw --batch-mode -f dessertj-core-java9/pom.xml install

    - name: Build dessertj-core with Maven
      run: . mvnw --batch-mode verify

    - name: Create .nojekyll
      run: touch target/apidocs/.nojekyll

    - name: Publish Javadocs
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target/apidocs # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deployed branch
