# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    # Resolving dependencies with Java 6 is not possible
    - name: Resolve Dependencies
      run: . mvnw -B dependency:go-offline

    - name: Set up JDK 1.6
      uses: actions/setup-java@v1
      with:
        java-version: 6

    - name: Build with Maven
      run: . mvnw -B verify

